source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'PDKTProgress' do
  pod "PDKTProgress", :path => "../"
end

target 'Tests' do
  pod "PDKTProgress", :path => "../"
  pod 'OCMockito', '~> 1.0'  
end
