source 'https://github.com/CocoaPods/Specs.git'

target 'PDKTProgress', :exclusive => true do
  pod "PDKTProgress", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PDKTProgress", :path => "../"
  pod 'OCMockito', '~> 1.0'  
end
